// Mocks generated by Mockito 5.4.4 from annotations
// in q_ez/test/presentation/screens/student/leaderboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:q_ez/domain/entities/user.dart' as _i2;
import 'package:q_ez/domain/repositories/user_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStudent_0 extends _i1.SmartFake implements _i2.Student {
  _FakeStudent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeacher_1 extends _i1.SmartFake implements _i2.Teacher {
  _FakeTeacher_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdmin_2 extends _i1.SmartFake implements _i2.Admin {
  _FakeAdmin_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppUser_3 extends _i1.SmartFake implements _i2.AppUser {
  _FakeAppUser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Student> getStudent(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getStudent,
          [id],
        ),
        returnValue: _i4.Future<_i2.Student>.value(_FakeStudent_0(
          this,
          Invocation.method(
            #getStudent,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Student>);

  @override
  _i4.Future<_i2.Teacher> getTeacher(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTeacher,
          [id],
        ),
        returnValue: _i4.Future<_i2.Teacher>.value(_FakeTeacher_1(
          this,
          Invocation.method(
            #getTeacher,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Teacher>);

  @override
  _i4.Future<_i2.Admin> getAdmin(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getAdmin,
          [id],
        ),
        returnValue: _i4.Future<_i2.Admin>.value(_FakeAdmin_2(
          this,
          Invocation.method(
            #getAdmin,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Admin>);

  @override
  _i4.Future<_i2.AppUser> getUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [id],
        ),
        returnValue: _i4.Future<_i2.AppUser>.value(_FakeAppUser_3(
          this,
          Invocation.method(
            #getUser,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.AppUser>);

  @override
  _i4.Future<void> updateStudentLevel(
    String? id,
    int? newLevel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStudentLevel,
          [
            id,
            newLevel,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateStudentStats(
    String? id,
    int? totalQuizzes,
    double? averageScore,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStudentStats,
          [
            id,
            totalQuizzes,
            averageScore,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> awardBadge(
    String? studentId,
    String? badgeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #awardBadge,
          [
            studentId,
            badgeId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Student>> getLeaderboard(int? limit) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaderboard,
          [limit],
        ),
        returnValue: _i4.Future<List<_i2.Student>>.value(<_i2.Student>[]),
      ) as _i4.Future<List<_i2.Student>>);

  @override
  _i4.Future<List<_i2.Student>> getTopStudentsForQuiz(
    String? quizId,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopStudentsForQuiz,
          [
            quizId,
            limit,
          ],
        ),
        returnValue: _i4.Future<List<_i2.Student>>.value(<_i2.Student>[]),
      ) as _i4.Future<List<_i2.Student>>);

  @override
  _i4.Future<List<_i2.AppUser>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i4.Future<List<_i2.AppUser>>.value(<_i2.AppUser>[]),
      ) as _i4.Future<List<_i2.AppUser>>);

  @override
  _i4.Future<List<_i2.Student>> getAllStudents() => (super.noSuchMethod(
        Invocation.method(
          #getAllStudents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Student>>.value(<_i2.Student>[]),
      ) as _i4.Future<List<_i2.Student>>);

  @override
  _i4.Future<List<_i2.Teacher>> getAllTeachers() => (super.noSuchMethod(
        Invocation.method(
          #getAllTeachers,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Teacher>>.value(<_i2.Teacher>[]),
      ) as _i4.Future<List<_i2.Teacher>>);

  @override
  _i4.Future<void> updateUser(_i2.AppUser? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createUserProfile(_i2.AppUser? user) => (super.noSuchMethod(
        Invocation.method(
          #createUserProfile,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
