// Firebase configuration for web platform
//
// Replace these placeholder values with your actual Firebase project configuration.
// You can find these values in the Firebase Console under:
//   Project Settings > General > Your apps > Web app
//
// For CI/CD pipelines, inject these values at build time using environment variables.
// Example (using sed or envsubst in your build script):
//   FIREBASE_API_KEY, FIREBASE_PROJECT_ID, FIREBASE_APP_ID, etc.
//
// Note: Flutter's firebase_core package reads configuration from firebase_options.dart
// (generated by FlutterFire CLI). This file is provided for any direct JS Firebase
// SDK usage (e.g., service workers or custom scripts).

const firebaseConfig = {
  apiKey: "YOUR_WEB_API_KEY",
  authDomain: "YOUR_PROJECT_ID.firebaseapp.com",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_PROJECT_ID.appspot.com",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "1:YOUR_APP_ID:web:YOUR_WEB_APP_ID",
  measurementId: "YOUR_MEASUREMENT_ID"
};

// Firebase is initialized by Flutter via firebase_core.
// Uncomment the lines below only if you need direct JS SDK initialization
// (e.g., for a custom service worker):
//
// import { initializeApp } from "https://www.gstatic.com/firebasejs/10.x.x/firebase-app.js";
// const app = initializeApp(firebaseConfig);
